# TODO: Set your WiFi AP interface name
interface=wlan1
driver=nl80211
# TODO: Set your WiFi SSID
ssid=MY_WIFI_SSID
channel=1
hw_mode=g
macaddr_acl=0
ignore_broadcast_ssid=0
auth_algs=1
wpa=2
# TODO: Set your WiFi passphrase (min 8 characters)
wpa_passphrase=CHANGE_ME_PASSPHRASE
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
wpa_ptk_rekey=0

