# TODO: Set your LiFi wireless interface name
interface=wlp2s0
driver=nl80211
# TODO: Set your LiFi SSID
ssid=MY_LIFI_SSID
channel=9
hw_mode=g
macaddr_acl=0
ignore_broadcast_ssid=0
auth_algs=1
wpa=3
# TODO: Set your LiFi passphrase (min 8 characters)
wpa_passphrase=CHANGE_ME_PASSPHRASE
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
is_primary=1
