network={
        # TODO: Must match WiFi AP SSID
        ssid="MY_WIFI_SSID"
        # TODO: Must match WiFi AP passphrase
        psk="CHANGE_ME_PASSPHRASE"
        proto=RSN
        key_mgmt=WPA-PSK
        pairwise=CCMP
}


